# config.yaml
potentials:
  - provider: "physics-ml"
    model_name: "MACE"
    precision: "64"
    position_scaling: 10.0
    output_scaling: 2623.368 # 4.184 * 627
    model_path: "../guardowl/tests/data/physics-ml/mace"
    device: "cuda"

  - provider: "openmm-ml"
    model_name: "ANI2x"

tests:
  - protocol: "alanine_dipeptide_test"
    env: "solution"
    ensemble: "npt"
    annealing: false
    nr_of_simulation_steps: 50
    temperature: 300

  - protocol: "alanine_dipeptide_test"
    env: "vacuum"
    ensemble: "npt"
    annealing: false
    nr_of_simulation_steps: 500
    temperature: 300

  - protocol: "small_molecule_test"
    smiles:
      [
        'CCOc1ccc2nc(/N=C\c3ccccc3O)sc2c1',
        'Cn1cc(Cl)c(/C=N/O)n1',
        'S=c1cc(-c2ccc(Cl)cc2)ss1',
      ]
    names: ["mol1", "mol2", "mol3"]
    temperature: [300, 400, 500]
    nr_of_simulation_steps: 500

  - protocol: "waterbox_test"
    edge_length: 25
    ensemble: "npt"
    annealing: false
    nr_of_simulation_steps: 50
    temperature: 300

  - protocol: "waterbox_test"
    edge_length: 15
    ensemble: "npt"
    annealing: false
    nr_of_simulation_steps: 50
    temperature: 500

  - protocol: "organic_liquid_test"
    molecule_name: ["ethane", "butane", "methanol"]
    nr_of_molecule: [100, 200, 300]
    ensemble: "npt"
    annealing: false
    nr_of_simulation_steps: 50
    nr_of_equilibration_steps: 50
    temperature: 300
