hipen_protocol:
  hipen_idx: 0
  nnp: "ani2x"
  implementation: "torchani"
  nr_of_simulation_steps: 5_000

waterbox_protocol:
  edge_length: 15
  ensemble: "npt"
  nnp: "ani2x"
  implementation: "torchani"
  annealing: false
  nr_of_simulation_steps: 5_000
