# config.yaml
tests:
  - protocol: "alanine_dipeptide_protocol"
    env: "solution"
    ensemble: "npt"
    nnp: "ani2x"
    implementation: "torchani"
    annealing: false
    nr_of_simulation_steps: 50
    temperature: 300

  - protocol: "alanine_dipeptide_protocol"
    env: "vacuum"
    ensemble: "npt"
    nnp: "ani2x"
    implementation: "torchani"
    annealing: false
    nr_of_simulation_steps: 5
    temperature: 300

  - protocol: "hipen_protocol"
    hipen_idx: [0, 1, 15]
    nnp: "ani2x"
    implementation: "nnpops"
    temperature: [300, 400, 500]
    nr_of_simulation_steps: 50

  - protocol: "waterbox_protocol"
    edge_length: 30
    ensemble: "npt"
    nnp: "ani2x"
    implementation: "nnpops"
    annealing: false
    nr_of_simulation_steps: 50
    temperature: 300

  - protocol: "waterbox_protocol"
    edge_length: 30
    ensemble: "npt"
    nnp: "ani2x"
    implementation: "nnpops"
    annealing: false
    nr_of_simulation_steps: 50
    temperature: 500

  - protocol: "pure_liquid_protocol"
    molecule_name: ["ethane", "butane"]
    nr_of_molecule: [100, 200]
    ensemble: "npt"
    nnp: "ani2x"
    implementation: "torchani"
    annealing: false
    nr_of_simulation_steps: 50
    nr_of_equilibration_steps: 50
    temperature: 300
