# config.yaml
potentials:
  - physicsml-model:
      - model_name: 'MACE'
      - precision: 64
      - position_scaling: 10.0
      - output_scaling: 4.184 * 627
      - model_path: "path_to_model"

  - openmmml:
      - model_name: "ANI2x"

tests:
  - protocol: "alanine_dipeptide_protocol"
    env: "solution"
    ensemble: "npt"
    nnp: "ani2x"
    annealing: false
    nr_of_simulation_steps: 50
    temperature: 300

  - protocol: "alanine_dipeptide_protocol"
    env: "vacuum"
    ensemble: "npt"
    nnp: "ani2x"
    annealing: false
    nr_of_simulation_steps: 500
    temperature: 300

  - protocol: "hipen_protocol"
    hipen_idx: [0, 1, 15]
    nnp: "ani2x"
    temperature: [300, 400, 500]
    nr_of_simulation_steps: 500

  - protocol: "waterbox_protocol"
    edge_length: 25
    ensemble: "npt"
    nnp: "ani2x"
    annealing: false
    nr_of_simulation_steps: 50
    temperature: 300

  - protocol: "waterbox_protocol"
    edge_length: 25
    ensemble: "npt"
    nnp: "ani2x"
    annealing: false
    nr_of_simulation_steps: 50
    temperature: 500

  - protocol: "pure_liquid_protocol"
    molecule_name: ["ethane", "butane", "methanol"]
    nr_of_molecule: [100, 200, 300]
    ensemble: "npt"
    nnp: "ani2x"
    annealing: false
    nr_of_simulation_steps: 50
    nr_of_equilibration_steps: 50
    temperature: 300
